/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.api;

import com.voicebase.sample.v3client.ApiException;
import com.voicebase.sample.v3client.model.VbErrorResponse;
import com.voicebase.sample.v3client.model.VbKey;
import com.voicebase.sample.v3client.model.VbKeyConfiguration;
import com.voicebase.sample.v3client.model.VbKeysResponse;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for KeyManagementApi
 */
@Ignore
public class KeyManagementApiTest {

    private final KeyManagementApi api = new KeyManagementApi();

    
    /**
     * Create API Key
     *
     * Create a new API key for the current user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createKeyTest() throws ApiException {
        VbKeyConfiguration key = null;
        VbKey response = api.createKey(key);

        // TODO: test validations
    }
    
    /**
     * Delete API key
     *
     * Delete and revoke this API key
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteKeyByIdTest() throws ApiException {
        String keyId = null;
        api.deleteKeyById(keyId);

        // TODO: test validations
    }
    
    /**
     * Retrieve details about an API key
     *
     * Get information about this API key
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKeyByIdTest() throws ApiException {
        String keyId = null;
        VbKey response = api.getKeyById(keyId);

        // TODO: test validations
    }
    
    /**
     * List API Keys
     *
     * Returns all current API keys for current user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKeysTest() throws ApiException {
        VbKeysResponse response = api.getKeys();

        // TODO: test validations
    }
    
}
