/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbCallbackFormatEnum;
import com.voicebase.sample.v3client.model.VbCallbackStreamEnum;
import com.voicebase.sample.v3client.model.VbCallbackTypeEnum;
import com.voicebase.sample.v3client.model.VbHttpMethodEnum;
import com.voicebase.sample.v3client.model.VbIncludeTypeEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbCallbackConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbCallbackConfiguration {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("method")
  private VbHttpMethodEnum method = null;

  @JsonProperty("type")
  private VbCallbackTypeEnum type = null;

  @JsonProperty("include")
  private java.util.List<VbIncludeTypeEnum> include = new java.util.ArrayList<VbIncludeTypeEnum>();

  @JsonProperty("stream")
  private VbCallbackStreamEnum stream = null;

  @JsonProperty("format")
  private VbCallbackFormatEnum format = null;

  public VbCallbackConfiguration url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public VbCallbackConfiguration method(VbHttpMethodEnum method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbHttpMethodEnum getMethod() {
    return method;
  }

  public void setMethod(VbHttpMethodEnum method) {
    this.method = method;
  }

  public VbCallbackConfiguration type(VbCallbackTypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbCallbackTypeEnum getType() {
    return type;
  }

  public void setType(VbCallbackTypeEnum type) {
    this.type = type;
  }

  public VbCallbackConfiguration include(java.util.List<VbIncludeTypeEnum> include) {
    this.include = include;
    return this;
  }

  public VbCallbackConfiguration addIncludeItem(VbIncludeTypeEnum includeItem) {
    this.include.add(includeItem);
    return this;
  }

   /**
   * Get include
   * @return include
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbIncludeTypeEnum> getInclude() {
    return include;
  }

  public void setInclude(java.util.List<VbIncludeTypeEnum> include) {
    this.include = include;
  }

  public VbCallbackConfiguration stream(VbCallbackStreamEnum stream) {
    this.stream = stream;
    return this;
  }

   /**
   * Get stream
   * @return stream
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbCallbackStreamEnum getStream() {
    return stream;
  }

  public void setStream(VbCallbackStreamEnum stream) {
    this.stream = stream;
  }

  public VbCallbackConfiguration format(VbCallbackFormatEnum format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbCallbackFormatEnum getFormat() {
    return format;
  }

  public void setFormat(VbCallbackFormatEnum format) {
    this.format = format;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbCallbackConfiguration vbCallbackConfiguration = (VbCallbackConfiguration) o;
    return Objects.equals(this.url, vbCallbackConfiguration.url) &&
        Objects.equals(this.method, vbCallbackConfiguration.method) &&
        Objects.equals(this.type, vbCallbackConfiguration.type) &&
        Objects.equals(this.include, vbCallbackConfiguration.include) &&
        Objects.equals(this.stream, vbCallbackConfiguration.stream) &&
        Objects.equals(this.format, vbCallbackConfiguration.format);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, method, type, include, stream, format);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbCallbackConfiguration {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    include: ").append(toIndentedString(include)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

