/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbClassifierModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbClassifierModelsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbClassifierModelsResponse {
  @JsonProperty("classifiers")
  private java.util.List<VbClassifierModel> classifiers = new java.util.ArrayList<VbClassifierModel>();

  public VbClassifierModelsResponse classifiers(java.util.List<VbClassifierModel> classifiers) {
    this.classifiers = classifiers;
    return this;
  }

  public VbClassifierModelsResponse addClassifiersItem(VbClassifierModel classifiersItem) {
    this.classifiers.add(classifiersItem);
    return this;
  }

   /**
   * Get classifiers
   * @return classifiers
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbClassifierModel> getClassifiers() {
    return classifiers;
  }

  public void setClassifiers(java.util.List<VbClassifierModel> classifiers) {
    this.classifiers = classifiers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbClassifierModelsResponse vbClassifierModelsResponse = (VbClassifierModelsResponse) o;
    return Objects.equals(this.classifiers, vbClassifierModelsResponse.classifiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classifiers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbClassifierModelsResponse {\n");
    
    sb.append("    classifiers: ").append(toIndentedString(classifiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

