/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbParameter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbClassifierConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbClassifierConfiguration {
  @JsonProperty("classifierId")
  private String classifierId = null;

  @JsonProperty("classifierName")
  private String classifierName = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("parameters")
  private java.util.List<VbParameter> parameters = new java.util.ArrayList<VbParameter>();

  public VbClassifierConfiguration classifierId(String classifierId) {
    this.classifierId = classifierId;
    return this;
  }

   /**
   * Classifier identifier, usually a UUID.
   * @return classifierId
  **/
  @ApiModelProperty(example = "null", value = "Classifier identifier, usually a UUID.")
  public String getClassifierId() {
    return classifierId;
  }

  public void setClassifierId(String classifierId) {
    this.classifierId = classifierId;
  }

  public VbClassifierConfiguration classifierName(String classifierName) {
    this.classifierName = classifierName;
    return this;
  }

   /**
   * A name identifying classifiers offered by Voicebase to all customers
   * @return classifierName
  **/
  @ApiModelProperty(example = "null", value = "A name identifying classifiers offered by Voicebase to all customers")
  public String getClassifierName() {
    return classifierName;
  }

  public void setClassifierName(String classifierName) {
    this.classifierName = classifierName;
  }

  public VbClassifierConfiguration version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Provide a specific version (e.g. \"3.1.3\"), specify a minimum (e.g. \"3.1+\") or get the \"latest\". Defaults to \"latest\" if not specified.
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "Provide a specific version (e.g. \"3.1.3\"), specify a minimum (e.g. \"3.1+\") or get the \"latest\". Defaults to \"latest\" if not specified.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public VbClassifierConfiguration parameters(java.util.List<VbParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public VbClassifierConfiguration addParametersItem(VbParameter parametersItem) {
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * List of parameter values to the classifier
   * @return parameters
  **/
  @ApiModelProperty(example = "null", value = "List of parameter values to the classifier")
  public java.util.List<VbParameter> getParameters() {
    return parameters;
  }

  public void setParameters(java.util.List<VbParameter> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbClassifierConfiguration vbClassifierConfiguration = (VbClassifierConfiguration) o;
    return Objects.equals(this.classifierId, vbClassifierConfiguration.classifierId) &&
        Objects.equals(this.classifierName, vbClassifierConfiguration.classifierName) &&
        Objects.equals(this.version, vbClassifierConfiguration.version) &&
        Objects.equals(this.parameters, vbClassifierConfiguration.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classifierId, classifierName, version, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbClassifierConfiguration {\n");
    
    sb.append("    classifierId: ").append(toIndentedString(classifierId)).append("\n");
    sb.append("    classifierName: ").append(toIndentedString(classifierName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

