/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbIngestConfiguration;
import com.voicebase.sample.v3client.model.VbKnowledgeConfiguration;
import com.voicebase.sample.v3client.model.VbPredictionConfiguration;
import com.voicebase.sample.v3client.model.VbPriorityEnum;
import com.voicebase.sample.v3client.model.VbPublishConfiguration;
import com.voicebase.sample.v3client.model.VbSpeechModelConfiguration;
import com.voicebase.sample.v3client.model.VbSpottingConfiguration;
import com.voicebase.sample.v3client.model.VbTranscriptConfiguration;
import com.voicebase.sample.v3client.model.VbVocabularyConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbConfiguration {
  @JsonProperty("speechModel")
  private VbSpeechModelConfiguration speechModel = null;

  @JsonProperty("additionalSpeechModels")
  private java.util.List<VbSpeechModelConfiguration> additionalSpeechModels = new java.util.ArrayList<VbSpeechModelConfiguration>();

  @JsonProperty("priority")
  private VbPriorityEnum priority = null;

  @JsonProperty("ingest")
  private VbIngestConfiguration ingest = null;

  @JsonProperty("prediction")
  private VbPredictionConfiguration prediction = null;

  @JsonProperty("spotting")
  private VbSpottingConfiguration spotting = null;

  @JsonProperty("knowledge")
  private VbKnowledgeConfiguration knowledge = null;

  @JsonProperty("transcript")
  private VbTranscriptConfiguration transcript = null;

  @JsonProperty("vocabularies")
  private java.util.List<VbVocabularyConfiguration> vocabularies = new java.util.ArrayList<VbVocabularyConfiguration>();

  @JsonProperty("publish")
  private VbPublishConfiguration publish = null;

  public VbConfiguration speechModel(VbSpeechModelConfiguration speechModel) {
    this.speechModel = speechModel;
    return this;
  }

   /**
   * Get speechModel
   * @return speechModel
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbSpeechModelConfiguration getSpeechModel() {
    return speechModel;
  }

  public void setSpeechModel(VbSpeechModelConfiguration speechModel) {
    this.speechModel = speechModel;
  }

  public VbConfiguration additionalSpeechModels(java.util.List<VbSpeechModelConfiguration> additionalSpeechModels) {
    this.additionalSpeechModels = additionalSpeechModels;
    return this;
  }

  public VbConfiguration addAdditionalSpeechModelsItem(VbSpeechModelConfiguration additionalSpeechModelsItem) {
    this.additionalSpeechModels.add(additionalSpeechModelsItem);
    return this;
  }

   /**
   * Allows to specify other languages to enable recognition when conversations occur in multiple languages
   * @return additionalSpeechModels
  **/
  @ApiModelProperty(example = "null", value = "Allows to specify other languages to enable recognition when conversations occur in multiple languages")
  public java.util.List<VbSpeechModelConfiguration> getAdditionalSpeechModels() {
    return additionalSpeechModels;
  }

  public void setAdditionalSpeechModels(java.util.List<VbSpeechModelConfiguration> additionalSpeechModels) {
    this.additionalSpeechModels = additionalSpeechModels;
  }

  public VbConfiguration priority(VbPriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbPriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(VbPriorityEnum priority) {
    this.priority = priority;
  }

  public VbConfiguration ingest(VbIngestConfiguration ingest) {
    this.ingest = ingest;
    return this;
  }

   /**
   * Get ingest
   * @return ingest
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbIngestConfiguration getIngest() {
    return ingest;
  }

  public void setIngest(VbIngestConfiguration ingest) {
    this.ingest = ingest;
  }

  public VbConfiguration prediction(VbPredictionConfiguration prediction) {
    this.prediction = prediction;
    return this;
  }

   /**
   * Get prediction
   * @return prediction
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbPredictionConfiguration getPrediction() {
    return prediction;
  }

  public void setPrediction(VbPredictionConfiguration prediction) {
    this.prediction = prediction;
  }

  public VbConfiguration spotting(VbSpottingConfiguration spotting) {
    this.spotting = spotting;
    return this;
  }

   /**
   * Get spotting
   * @return spotting
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbSpottingConfiguration getSpotting() {
    return spotting;
  }

  public void setSpotting(VbSpottingConfiguration spotting) {
    this.spotting = spotting;
  }

  public VbConfiguration knowledge(VbKnowledgeConfiguration knowledge) {
    this.knowledge = knowledge;
    return this;
  }

   /**
   * Get knowledge
   * @return knowledge
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbKnowledgeConfiguration getKnowledge() {
    return knowledge;
  }

  public void setKnowledge(VbKnowledgeConfiguration knowledge) {
    this.knowledge = knowledge;
  }

  public VbConfiguration transcript(VbTranscriptConfiguration transcript) {
    this.transcript = transcript;
    return this;
  }

   /**
   * Get transcript
   * @return transcript
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbTranscriptConfiguration getTranscript() {
    return transcript;
  }

  public void setTranscript(VbTranscriptConfiguration transcript) {
    this.transcript = transcript;
  }

  public VbConfiguration vocabularies(java.util.List<VbVocabularyConfiguration> vocabularies) {
    this.vocabularies = vocabularies;
    return this;
  }

  public VbConfiguration addVocabulariesItem(VbVocabularyConfiguration vocabulariesItem) {
    this.vocabularies.add(vocabulariesItem);
    return this;
  }

   /**
   * Get vocabularies
   * @return vocabularies
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabularyConfiguration> getVocabularies() {
    return vocabularies;
  }

  public void setVocabularies(java.util.List<VbVocabularyConfiguration> vocabularies) {
    this.vocabularies = vocabularies;
  }

  public VbConfiguration publish(VbPublishConfiguration publish) {
    this.publish = publish;
    return this;
  }

   /**
   * Get publish
   * @return publish
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbPublishConfiguration getPublish() {
    return publish;
  }

  public void setPublish(VbPublishConfiguration publish) {
    this.publish = publish;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbConfiguration vbConfiguration = (VbConfiguration) o;
    return Objects.equals(this.speechModel, vbConfiguration.speechModel) &&
        Objects.equals(this.additionalSpeechModels, vbConfiguration.additionalSpeechModels) &&
        Objects.equals(this.priority, vbConfiguration.priority) &&
        Objects.equals(this.ingest, vbConfiguration.ingest) &&
        Objects.equals(this.prediction, vbConfiguration.prediction) &&
        Objects.equals(this.spotting, vbConfiguration.spotting) &&
        Objects.equals(this.knowledge, vbConfiguration.knowledge) &&
        Objects.equals(this.transcript, vbConfiguration.transcript) &&
        Objects.equals(this.vocabularies, vbConfiguration.vocabularies) &&
        Objects.equals(this.publish, vbConfiguration.publish);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speechModel, additionalSpeechModels, priority, ingest, prediction, spotting, knowledge, transcript, vocabularies, publish);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbConfiguration {\n");
    
    sb.append("    speechModel: ").append(toIndentedString(speechModel)).append("\n");
    sb.append("    additionalSpeechModels: ").append(toIndentedString(additionalSpeechModels)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    ingest: ").append(toIndentedString(ingest)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    spotting: ").append(toIndentedString(spotting)).append("\n");
    sb.append("    knowledge: ").append(toIndentedString(knowledge)).append("\n");
    sb.append("    transcript: ").append(toIndentedString(transcript)).append("\n");
    sb.append("    vocabularies: ").append(toIndentedString(vocabularies)).append("\n");
    sb.append("    publish: ").append(toIndentedString(publish)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

