/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbContentFilteringConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbContentFilteringConfiguration {
  @JsonProperty("enableProfanityFiltering")
  private Boolean enableProfanityFiltering = true;

  public VbContentFilteringConfiguration enableProfanityFiltering(Boolean enableProfanityFiltering) {
    this.enableProfanityFiltering = enableProfanityFiltering;
    return this;
  }

   /**
   * Whether swear word filtering is enabled or not
   * @return enableProfanityFiltering
  **/
  @ApiModelProperty(example = "null", value = "Whether swear word filtering is enabled or not")
  public Boolean getEnableProfanityFiltering() {
    return enableProfanityFiltering;
  }

  public void setEnableProfanityFiltering(Boolean enableProfanityFiltering) {
    this.enableProfanityFiltering = enableProfanityFiltering;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbContentFilteringConfiguration vbContentFilteringConfiguration = (VbContentFilteringConfiguration) o;
    return Objects.equals(this.enableProfanityFiltering, vbContentFilteringConfiguration.enableProfanityFiltering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableProfanityFiltering);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbContentFilteringConfiguration {\n");
    
    sb.append("    enableProfanityFiltering: ").append(toIndentedString(enableProfanityFiltering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

