/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbDetectorModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbDetectorModelsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbDetectorModelsResponse {
  @JsonProperty("detectors")
  private java.util.List<VbDetectorModel> detectors = new java.util.ArrayList<VbDetectorModel>();

  public VbDetectorModelsResponse detectors(java.util.List<VbDetectorModel> detectors) {
    this.detectors = detectors;
    return this;
  }

  public VbDetectorModelsResponse addDetectorsItem(VbDetectorModel detectorsItem) {
    this.detectors.add(detectorsItem);
    return this;
  }

   /**
   * Get detectors
   * @return detectors
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbDetectorModel> getDetectors() {
    return detectors;
  }

  public void setDetectors(java.util.List<VbDetectorModel> detectors) {
    this.detectors = detectors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbDetectorModelsResponse vbDetectorModelsResponse = (VbDetectorModelsResponse) o;
    return Objects.equals(this.detectors, vbDetectorModelsResponse.detectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbDetectorModelsResponse {\n");
    
    sb.append("    detectors: ").append(toIndentedString(detectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

