/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbDetection;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbDetector
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbDetector {
  @JsonProperty("detectorId")
  private String detectorId = null;

  @JsonProperty("detectorName")
  private String detectorName = null;

  @JsonProperty("detectorDisplayName")
  private String detectorDisplayName = null;

  @JsonProperty("detectorType")
  private String detectorType = null;

  @JsonProperty("detections")
  private java.util.List<VbDetection> detections = new java.util.ArrayList<VbDetection>();

  public VbDetector detectorId(String detectorId) {
    this.detectorId = detectorId;
    return this;
  }

   /**
   * Get detectorId
   * @return detectorId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDetectorId() {
    return detectorId;
  }

  public void setDetectorId(String detectorId) {
    this.detectorId = detectorId;
  }

  public VbDetector detectorName(String detectorName) {
    this.detectorName = detectorName;
    return this;
  }

   /**
   * Get detectorName
   * @return detectorName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDetectorName() {
    return detectorName;
  }

  public void setDetectorName(String detectorName) {
    this.detectorName = detectorName;
  }

  public VbDetector detectorDisplayName(String detectorDisplayName) {
    this.detectorDisplayName = detectorDisplayName;
    return this;
  }

   /**
   * Get detectorDisplayName
   * @return detectorDisplayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDetectorDisplayName() {
    return detectorDisplayName;
  }

  public void setDetectorDisplayName(String detectorDisplayName) {
    this.detectorDisplayName = detectorDisplayName;
  }

  public VbDetector detectorType(String detectorType) {
    this.detectorType = detectorType;
    return this;
  }

   /**
   * Get detectorType
   * @return detectorType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDetectorType() {
    return detectorType;
  }

  public void setDetectorType(String detectorType) {
    this.detectorType = detectorType;
  }

  public VbDetector detections(java.util.List<VbDetection> detections) {
    this.detections = detections;
    return this;
  }

  public VbDetector addDetectionsItem(VbDetection detectionsItem) {
    this.detections.add(detectionsItem);
    return this;
  }

   /**
   * Get detections
   * @return detections
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbDetection> getDetections() {
    return detections;
  }

  public void setDetections(java.util.List<VbDetection> detections) {
    this.detections = detections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbDetector vbDetector = (VbDetector) o;
    return Objects.equals(this.detectorId, vbDetector.detectorId) &&
        Objects.equals(this.detectorName, vbDetector.detectorName) &&
        Objects.equals(this.detectorDisplayName, vbDetector.detectorDisplayName) &&
        Objects.equals(this.detectorType, vbDetector.detectorType) &&
        Objects.equals(this.detections, vbDetector.detections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectorId, detectorName, detectorDisplayName, detectorType, detections);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbDetector {\n");
    
    sb.append("    detectorId: ").append(toIndentedString(detectorId)).append("\n");
    sb.append("    detectorName: ").append(toIndentedString(detectorName)).append("\n");
    sb.append("    detectorDisplayName: ").append(toIndentedString(detectorDisplayName)).append("\n");
    sb.append("    detectorType: ").append(toIndentedString(detectorType)).append("\n");
    sb.append("    detections: ").append(toIndentedString(detections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

