/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbError;
import com.voicebase.sample.v3client.model.VbMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbErrorResponse {
  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("errors")
  private java.util.List<VbError> errors = new java.util.ArrayList<VbError>();

  @JsonProperty("warnings")
  private java.util.List<VbMessage> warnings = new java.util.ArrayList<VbMessage>();

  @JsonProperty("reference")
  private String reference = null;

  public VbErrorResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Status Code
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Status Code")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public VbErrorResponse errors(java.util.List<VbError> errors) {
    this.errors = errors;
    return this;
  }

  public VbErrorResponse addErrorsItem(VbError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * The errors
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "The errors")
  public java.util.List<VbError> getErrors() {
    return errors;
  }

  public void setErrors(java.util.List<VbError> errors) {
    this.errors = errors;
  }

  public VbErrorResponse warnings(java.util.List<VbMessage> warnings) {
    this.warnings = warnings;
    return this;
  }

  public VbErrorResponse addWarningsItem(VbMessage warningsItem) {
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * The warnings
   * @return warnings
  **/
  @ApiModelProperty(example = "null", value = "The warnings")
  public java.util.List<VbMessage> getWarnings() {
    return warnings;
  }

  public void setWarnings(java.util.List<VbMessage> warnings) {
    this.warnings = warnings;
  }

  public VbErrorResponse reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * ref.
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "ref.")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbErrorResponse vbErrorResponse = (VbErrorResponse) o;
    return Objects.equals(this.status, vbErrorResponse.status) &&
        Objects.equals(this.errors, vbErrorResponse.errors) &&
        Objects.equals(this.warnings, vbErrorResponse.warnings) &&
        Objects.equals(this.reference, vbErrorResponse.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, errors, warnings, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbErrorResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

