/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbFrequency
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbFrequency {
  @JsonProperty("e")
  private Double e = null;

  @JsonProperty("f")
  private Double f = null;

  public VbFrequency e(Double e) {
    this.e = e;
    return this;
  }

   /**
   * Get e
   * @return e
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getE() {
    return e;
  }

  public void setE(Double e) {
    this.e = e;
  }

  public VbFrequency f(Double f) {
    this.f = f;
    return this;
  }

   /**
   * Get f
   * @return f
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getF() {
    return f;
  }

  public void setF(Double f) {
    this.f = f;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbFrequency vbFrequency = (VbFrequency) o;
    return Objects.equals(this.e, vbFrequency.e) &&
        Objects.equals(this.f, vbFrequency.f);
  }

  @Override
  public int hashCode() {
    return Objects.hash(e, f);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbFrequency {\n");
    
    sb.append("    e: ").append(toIndentedString(e)).append("\n");
    sb.append("    f: ").append(toIndentedString(f)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

