/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbKeyword;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbGroup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbGroup {
  @JsonProperty("groupName")
  private String groupName = null;

  @JsonProperty("spotted")
  private Boolean spotted = null;

  @JsonProperty("score")
  private Double score = null;

  @JsonProperty("spottedKeywords")
  private java.util.List<VbKeyword> spottedKeywords = new java.util.ArrayList<VbKeyword>();

  public VbGroup groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public VbGroup spotted(Boolean spotted) {
    this.spotted = spotted;
    return this;
  }

   /**
   * Get spotted
   * @return spotted
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSpotted() {
    return spotted;
  }

  public void setSpotted(Boolean spotted) {
    this.spotted = spotted;
  }

  public VbGroup score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }

  public VbGroup spottedKeywords(java.util.List<VbKeyword> spottedKeywords) {
    this.spottedKeywords = spottedKeywords;
    return this;
  }

  public VbGroup addSpottedKeywordsItem(VbKeyword spottedKeywordsItem) {
    this.spottedKeywords.add(spottedKeywordsItem);
    return this;
  }

   /**
   * Get spottedKeywords
   * @return spottedKeywords
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbKeyword> getSpottedKeywords() {
    return spottedKeywords;
  }

  public void setSpottedKeywords(java.util.List<VbKeyword> spottedKeywords) {
    this.spottedKeywords = spottedKeywords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbGroup vbGroup = (VbGroup) o;
    return Objects.equals(this.groupName, vbGroup.groupName) &&
        Objects.equals(this.spotted, vbGroup.spotted) &&
        Objects.equals(this.score, vbGroup.score) &&
        Objects.equals(this.spottedKeywords, vbGroup.spottedKeywords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, spotted, score, spottedKeywords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbGroup {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    spotted: ").append(toIndentedString(spotted)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    spottedKeywords: ").append(toIndentedString(spottedKeywords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

