/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * VbKey
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbKey {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("bearerToken")
  private String bearerToken = null;

  @JsonProperty("lastSix")
  private String lastSix = null;

  @JsonProperty("issued")
  private OffsetDateTime issued = null;

  @JsonProperty("expirationDate")
  private OffsetDateTime expirationDate = null;

  @JsonProperty("expired")
  private Boolean expired = null;

  @JsonProperty("scope")
  private String scope = null;

  public VbKey id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VbKey bearerToken(String bearerToken) {
    this.bearerToken = bearerToken;
    return this;
  }

   /**
   * Get bearerToken
   * @return bearerToken
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBearerToken() {
    return bearerToken;
  }

  public void setBearerToken(String bearerToken) {
    this.bearerToken = bearerToken;
  }

  public VbKey lastSix(String lastSix) {
    this.lastSix = lastSix;
    return this;
  }

   /**
   * Get lastSix
   * @return lastSix
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastSix() {
    return lastSix;
  }

  public void setLastSix(String lastSix) {
    this.lastSix = lastSix;
  }

  public VbKey issued(OffsetDateTime issued) {
    this.issued = issued;
    return this;
  }

   /**
   * Get issued
   * @return issued
  **/
  @ApiModelProperty(example = "null", value = "")
  public OffsetDateTime getIssued() {
    return issued;
  }

  public void setIssued(OffsetDateTime issued) {
    this.issued = issued;
  }

  public VbKey expirationDate(OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public OffsetDateTime getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
  }

  public VbKey expired(Boolean expired) {
    this.expired = expired;
    return this;
  }

   /**
   * Get expired
   * @return expired
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getExpired() {
    return expired;
  }

  public void setExpired(Boolean expired) {
    this.expired = expired;
  }

  public VbKey scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbKey vbKey = (VbKey) o;
    return Objects.equals(this.id, vbKey.id) &&
        Objects.equals(this.bearerToken, vbKey.bearerToken) &&
        Objects.equals(this.lastSix, vbKey.lastSix) &&
        Objects.equals(this.issued, vbKey.issued) &&
        Objects.equals(this.expirationDate, vbKey.expirationDate) &&
        Objects.equals(this.expired, vbKey.expired) &&
        Objects.equals(this.scope, vbKey.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bearerToken, lastSix, issued, expirationDate, expired, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbKey {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bearerToken: ").append(toIndentedString(bearerToken)).append("\n");
    sb.append("    lastSix: ").append(toIndentedString(lastSix)).append("\n");
    sb.append("    issued: ").append(toIndentedString(issued)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

