/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbKnowledgeConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbKnowledgeConfiguration {
  @JsonProperty("enableDiscovery")
  private Boolean enableDiscovery = false;

  @JsonProperty("enableExternalDataSources")
  private Boolean enableExternalDataSources = true;

  public VbKnowledgeConfiguration enableDiscovery(Boolean enableDiscovery) {
    this.enableDiscovery = enableDiscovery;
    return this;
  }

   /**
   * Whether knowledge discovery is enabled or not
   * @return enableDiscovery
  **/
  @ApiModelProperty(example = "null", value = "Whether knowledge discovery is enabled or not")
  public Boolean getEnableDiscovery() {
    return enableDiscovery;
  }

  public void setEnableDiscovery(Boolean enableDiscovery) {
    this.enableDiscovery = enableDiscovery;
  }

  public VbKnowledgeConfiguration enableExternalDataSources(Boolean enableExternalDataSources) {
    this.enableExternalDataSources = enableExternalDataSources;
    return this;
  }

   /**
   * Whether semantic discovery is allowed to use external data sources or not
   * @return enableExternalDataSources
  **/
  @ApiModelProperty(example = "null", value = "Whether semantic discovery is allowed to use external data sources or not")
  public Boolean getEnableExternalDataSources() {
    return enableExternalDataSources;
  }

  public void setEnableExternalDataSources(Boolean enableExternalDataSources) {
    this.enableExternalDataSources = enableExternalDataSources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbKnowledgeConfiguration vbKnowledgeConfiguration = (VbKnowledgeConfiguration) o;
    return Objects.equals(this.enableDiscovery, vbKnowledgeConfiguration.enableDiscovery) &&
        Objects.equals(this.enableExternalDataSources, vbKnowledgeConfiguration.enableExternalDataSources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableDiscovery, enableExternalDataSources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbKnowledgeConfiguration {\n");
    
    sb.append("    enableDiscovery: ").append(toIndentedString(enableDiscovery)).append("\n");
    sb.append("    enableExternalDataSources: ").append(toIndentedString(enableExternalDataSources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

