/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.VbMetadata;
import com.voicebase.sample.v3client.model.VbStatusEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * VbMediaSummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbMediaSummary {
  @JsonProperty("formatVersion")
  private String formatVersion = null;

  @JsonProperty("mediaId")
  private String mediaId = null;

  @JsonProperty("status")
  private VbStatusEnum status = null;

  @JsonProperty("dateCreated")
  private OffsetDateTime dateCreated = null;

  @JsonProperty("metadata")
  private VbMetadata metadata = null;

  public VbMediaSummary formatVersion(String formatVersion) {
    this.formatVersion = formatVersion;
    return this;
  }

   /**
   * Media format version. E.g. 3.0.1
   * @return formatVersion
  **/
  @ApiModelProperty(example = "null", value = "Media format version. E.g. 3.0.1")
  public String getFormatVersion() {
    return formatVersion;
  }

  public void setFormatVersion(String formatVersion) {
    this.formatVersion = formatVersion;
  }

  public VbMediaSummary mediaId(String mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Media unique identifier.
   * @return mediaId
  **/
  @ApiModelProperty(example = "null", value = "Media unique identifier.")
  public String getMediaId() {
    return mediaId;
  }

  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }

  public VbMediaSummary status(VbStatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Processing state.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Processing state.")
  public VbStatusEnum getStatus() {
    return status;
  }

  public void setStatus(VbStatusEnum status) {
    this.status = status;
  }

  public VbMediaSummary dateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Creation timestamp
   * @return dateCreated
  **/
  @ApiModelProperty(example = "null", value = "Creation timestamp")
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }

  public VbMediaSummary metadata(VbMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * User defined data associated with this record.
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "User defined data associated with this record.")
  public VbMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(VbMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbMediaSummary vbMediaSummary = (VbMediaSummary) o;
    return Objects.equals(this.formatVersion, vbMediaSummary.formatVersion) &&
        Objects.equals(this.mediaId, vbMediaSummary.mediaId) &&
        Objects.equals(this.status, vbMediaSummary.status) &&
        Objects.equals(this.dateCreated, vbMediaSummary.dateCreated) &&
        Objects.equals(this.metadata, vbMediaSummary.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formatVersion, mediaId, status, dateCreated, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbMediaSummary {\n");
    
    sb.append("    formatVersion: ").append(toIndentedString(formatVersion)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

