/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbMediaSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbMediaQueryResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbMediaQueryResponse {
  @JsonProperty("media")
  private java.util.List<VbMediaSummary> media = new java.util.ArrayList<VbMediaSummary>();

  public VbMediaQueryResponse media(java.util.List<VbMediaSummary> media) {
    this.media = media;
    return this;
  }

  public VbMediaQueryResponse addMediaItem(VbMediaSummary mediaItem) {
    this.media.add(mediaItem);
    return this;
  }

   /**
   * Get media
   * @return media
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbMediaSummary> getMedia() {
    return media;
  }

  public void setMedia(java.util.List<VbMediaSummary> media) {
    this.media = media;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbMediaQueryResponse vbMediaQueryResponse = (VbMediaQueryResponse) o;
    return Objects.equals(this.media, vbMediaQueryResponse.media);
  }

  @Override
  public int hashCode() {
    return Objects.hash(media);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbMediaQueryResponse {\n");
    
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

