/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbJob;
import com.voicebase.sample.v3client.model.VbKnowledge;
import com.voicebase.sample.v3client.model.VbMediaSummary;
import com.voicebase.sample.v3client.model.VbMessage;
import com.voicebase.sample.v3client.model.VbMetadata;
import com.voicebase.sample.v3client.model.VbPrediction;
import com.voicebase.sample.v3client.model.VbSpotting;
import com.voicebase.sample.v3client.model.VbStatusEnum;
import com.voicebase.sample.v3client.model.VbStream;
import com.voicebase.sample.v3client.model.VbTranscript;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * VbMedia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbMedia {
  @JsonProperty("formatVersion")
  private String formatVersion = null;

  @JsonProperty("mediaId")
  private String mediaId = null;

  @JsonProperty("status")
  private VbStatusEnum status = null;

  @JsonProperty("dateCreated")
  private OffsetDateTime dateCreated = null;

  @JsonProperty("metadata")
  private VbMetadata metadata = null;

  @JsonProperty("mediaContentType")
  private String mediaContentType = null;

  @JsonProperty("length")
  private Long length = null;

  @JsonProperty("knowledge")
  private VbKnowledge knowledge = null;

  @JsonProperty("spotting")
  private VbSpotting spotting = null;

  @JsonProperty("prediction")
  private VbPrediction prediction = null;

  @JsonProperty("transcript")
  private VbTranscript transcript = null;

  @JsonProperty("warnings")
  private java.util.List<VbMessage> warnings = new java.util.ArrayList<VbMessage>();

  @JsonProperty("streams")
  private java.util.List<VbStream> streams = new java.util.ArrayList<VbStream>();

  @JsonProperty("_job")
  private VbJob job = null;

  public VbMedia formatVersion(String formatVersion) {
    this.formatVersion = formatVersion;
    return this;
  }

   /**
   * Media format version. E.g. 3.0.1
   * @return formatVersion
  **/
  @ApiModelProperty(example = "null", value = "Media format version. E.g. 3.0.1")
  public String getFormatVersion() {
    return formatVersion;
  }

  public void setFormatVersion(String formatVersion) {
    this.formatVersion = formatVersion;
  }

  public VbMedia mediaId(String mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Media unique identifier.
   * @return mediaId
  **/
  @ApiModelProperty(example = "null", value = "Media unique identifier.")
  public String getMediaId() {
    return mediaId;
  }

  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }

  public VbMedia status(VbStatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Processing state.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Processing state.")
  public VbStatusEnum getStatus() {
    return status;
  }

  public void setStatus(VbStatusEnum status) {
    this.status = status;
  }

  public VbMedia dateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Creation timestamp
   * @return dateCreated
  **/
  @ApiModelProperty(example = "null", value = "Creation timestamp")
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }

  public VbMedia metadata(VbMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * User defined data associated with this record.
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "User defined data associated with this record.")
  public VbMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(VbMetadata metadata) {
    this.metadata = metadata;
  }

  public VbMedia mediaContentType(String mediaContentType) {
    this.mediaContentType = mediaContentType;
    return this;
  }

   /**
   * The MIME type of the media submitted for processing. E.g. audio/x-wav, audio/mpeg
   * @return mediaContentType
  **/
  @ApiModelProperty(example = "null", value = "The MIME type of the media submitted for processing. E.g. audio/x-wav, audio/mpeg")
  public String getMediaContentType() {
    return mediaContentType;
  }

  public void setMediaContentType(String mediaContentType) {
    this.mediaContentType = mediaContentType;
  }

  public VbMedia length(Long length) {
    this.length = length;
    return this;
  }

   /**
   * Duration of the audio/video submitted for processing expressed in milliseconds
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "Duration of the audio/video submitted for processing expressed in milliseconds")
  public Long getLength() {
    return length;
  }

  public void setLength(Long length) {
    this.length = length;
  }

  public VbMedia knowledge(VbKnowledge knowledge) {
    this.knowledge = knowledge;
    return this;
  }

   /**
   * Semantic knowledge discovery section. If knoweledge discovery was requested, this section contains the results.
   * @return knowledge
  **/
  @ApiModelProperty(example = "null", value = "Semantic knowledge discovery section. If knoweledge discovery was requested, this section contains the results.")
  public VbKnowledge getKnowledge() {
    return knowledge;
  }

  public void setKnowledge(VbKnowledge knowledge) {
    this.knowledge = knowledge;
  }

  public VbMedia spotting(VbSpotting spotting) {
    this.spotting = spotting;
    return this;
  }

   /**
   * If kewyword spotting was requested, this section contains the results.
   * @return spotting
  **/
  @ApiModelProperty(example = "null", value = "If kewyword spotting was requested, this section contains the results.")
  public VbSpotting getSpotting() {
    return spotting;
  }

  public void setSpotting(VbSpotting spotting) {
    this.spotting = spotting;
  }

  public VbMedia prediction(VbPrediction prediction) {
    this.prediction = prediction;
    return this;
  }

   /**
   * If any predictions (classifiers, detectors) were requested, this section contains the results.
   * @return prediction
  **/
  @ApiModelProperty(example = "null", value = "If any predictions (classifiers, detectors) were requested, this section contains the results.")
  public VbPrediction getPrediction() {
    return prediction;
  }

  public void setPrediction(VbPrediction prediction) {
    this.prediction = prediction;
  }

  public VbMedia transcript(VbTranscript transcript) {
    this.transcript = transcript;
    return this;
  }

   /**
   * This section contains the transcript in a variety of formats
   * @return transcript
  **/
  @ApiModelProperty(example = "null", value = "This section contains the transcript in a variety of formats")
  public VbTranscript getTranscript() {
    return transcript;
  }

  public void setTranscript(VbTranscript transcript) {
    this.transcript = transcript;
  }

  public VbMedia warnings(java.util.List<VbMessage> warnings) {
    this.warnings = warnings;
    return this;
  }

  public VbMedia addWarningsItem(VbMessage warningsItem) {
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * This section contains warnings about the media
   * @return warnings
  **/
  @ApiModelProperty(example = "null", value = "This section contains warnings about the media")
  public java.util.List<VbMessage> getWarnings() {
    return warnings;
  }

  public void setWarnings(java.util.List<VbMessage> warnings) {
    this.warnings = warnings;
  }

  public VbMedia streams(java.util.List<VbStream> streams) {
    this.streams = streams;
    return this;
  }

  public VbMedia addStreamsItem(VbStream streamsItem) {
    this.streams.add(streamsItem);
    return this;
  }

   /**
   * Theaudio/video streams available.
   * @return streams
  **/
  @ApiModelProperty(example = "null", value = "Theaudio/video streams available.")
  public java.util.List<VbStream> getStreams() {
    return streams;
  }

  public void setStreams(java.util.List<VbStream> streams) {
    this.streams = streams;
  }

  public VbMedia job(VbJob job) {
    this.job = job;
    return this;
  }

   /**
   * Get job
   * @return job
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbJob getJob() {
    return job;
  }

  public void setJob(VbJob job) {
    this.job = job;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbMedia vbMedia = (VbMedia) o;
    return Objects.equals(this.formatVersion, vbMedia.formatVersion) &&
        Objects.equals(this.mediaId, vbMedia.mediaId) &&
        Objects.equals(this.status, vbMedia.status) &&
        Objects.equals(this.dateCreated, vbMedia.dateCreated) &&
        Objects.equals(this.metadata, vbMedia.metadata) &&
        Objects.equals(this.mediaContentType, vbMedia.mediaContentType) &&
        Objects.equals(this.length, vbMedia.length) &&
        Objects.equals(this.knowledge, vbMedia.knowledge) &&
        Objects.equals(this.spotting, vbMedia.spotting) &&
        Objects.equals(this.prediction, vbMedia.prediction) &&
        Objects.equals(this.transcript, vbMedia.transcript) &&
        Objects.equals(this.warnings, vbMedia.warnings) &&
        Objects.equals(this.streams, vbMedia.streams) &&
        Objects.equals(this.job, vbMedia.job);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formatVersion, mediaId, status, dateCreated, metadata, mediaContentType, length, knowledge, spotting, prediction, transcript, warnings, streams, job);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbMedia {\n");
    
    sb.append("    formatVersion: ").append(toIndentedString(formatVersion)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    mediaContentType: ").append(toIndentedString(mediaContentType)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    knowledge: ").append(toIndentedString(knowledge)).append("\n");
    sb.append("    spotting: ").append(toIndentedString(spotting)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    transcript: ").append(toIndentedString(transcript)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    streams: ").append(toIndentedString(streams)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

