/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbProgressTask;
import com.voicebase.sample.v3client.model.VbTaskStatusEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbProgress
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbProgress {
  @JsonProperty("finish")
  private String finish = null;

  @JsonProperty("jobId")
  private String jobId = null;

  @JsonProperty("start")
  private String start = null;

  @JsonProperty("status")
  private VbTaskStatusEnum status = null;

  @JsonProperty("tasks")
  private java.util.List<VbProgressTask> tasks = new java.util.ArrayList<VbProgressTask>();

  public VbProgress finish(String finish) {
    this.finish = finish;
    return this;
  }

   /**
   * Get finish
   * @return finish
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFinish() {
    return finish;
  }

  public void setFinish(String finish) {
    this.finish = finish;
  }

  public VbProgress jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public VbProgress start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public VbProgress status(VbTaskStatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbTaskStatusEnum getStatus() {
    return status;
  }

  public void setStatus(VbTaskStatusEnum status) {
    this.status = status;
  }

  public VbProgress tasks(java.util.List<VbProgressTask> tasks) {
    this.tasks = tasks;
    return this;
  }

  public VbProgress addTasksItem(VbProgressTask tasksItem) {
    this.tasks.add(tasksItem);
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbProgressTask> getTasks() {
    return tasks;
  }

  public void setTasks(java.util.List<VbProgressTask> tasks) {
    this.tasks = tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbProgress vbProgress = (VbProgress) o;
    return Objects.equals(this.finish, vbProgress.finish) &&
        Objects.equals(this.jobId, vbProgress.jobId) &&
        Objects.equals(this.start, vbProgress.start) &&
        Objects.equals(this.status, vbProgress.status) &&
        Objects.equals(this.tasks, vbProgress.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finish, jobId, start, status, tasks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbProgress {\n");
    
    sb.append("    finish: ").append(toIndentedString(finish)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

