/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbCallbackConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbPublishConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbPublishConfiguration {
  @JsonProperty("callbacks")
  private java.util.List<VbCallbackConfiguration> callbacks = new java.util.ArrayList<VbCallbackConfiguration>();

  public VbPublishConfiguration callbacks(java.util.List<VbCallbackConfiguration> callbacks) {
    this.callbacks = callbacks;
    return this;
  }

  public VbPublishConfiguration addCallbacksItem(VbCallbackConfiguration callbacksItem) {
    this.callbacks.add(callbacksItem);
    return this;
  }

   /**
   * Get callbacks
   * @return callbacks
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbCallbackConfiguration> getCallbacks() {
    return callbacks;
  }

  public void setCallbacks(java.util.List<VbCallbackConfiguration> callbacks) {
    this.callbacks = callbacks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbPublishConfiguration vbPublishConfiguration = (VbPublishConfiguration) o;
    return Objects.equals(this.callbacks, vbPublishConfiguration.callbacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbacks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbPublishConfiguration {\n");
    
    sb.append("    callbacks: ").append(toIndentedString(callbacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

