/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbSpeechModelConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbSpeechModelConfiguration {
  @JsonProperty("language")
  private String language = null;

  @JsonProperty("features")
  private java.util.List<String> features = new java.util.ArrayList<String>();

  @JsonProperty("extensions")
  private java.util.List<String> extensions = new java.util.ArrayList<String>();

  public VbSpeechModelConfiguration language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Specifies the language using the ISO-639-1 standard two-letter code followed by a dash and a non-standarized region code.
   * @return language
  **/
  @ApiModelProperty(example = "null", value = "Specifies the language using the ISO-639-1 standard two-letter code followed by a dash and a non-standarized region code.")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public VbSpeechModelConfiguration features(java.util.List<String> features) {
    this.features = features;
    return this;
  }

  public VbSpeechModelConfiguration addFeaturesItem(String featuresItem) {
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Allows to turn on additional features of the speech engine
   * @return features
  **/
  @ApiModelProperty(example = "null", value = "Allows to turn on additional features of the speech engine")
  public java.util.List<String> getFeatures() {
    return features;
  }

  public void setFeatures(java.util.List<String> features) {
    this.features = features;
  }

  public VbSpeechModelConfiguration extensions(java.util.List<String> extensions) {
    this.extensions = extensions;
    return this;
  }

  public VbSpeechModelConfiguration addExtensionsItem(String extensionsItem) {
    this.extensions.add(extensionsItem);
    return this;
  }

   /**
   * This allows to request speech recognition with additional extensions for specific jargon or use cases with the purpose to improve transcription accuracy
   * @return extensions
  **/
  @ApiModelProperty(example = "null", value = "This allows to request speech recognition with additional extensions for specific jargon or use cases with the purpose to improve transcription accuracy")
  public java.util.List<String> getExtensions() {
    return extensions;
  }

  public void setExtensions(java.util.List<String> extensions) {
    this.extensions = extensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbSpeechModelConfiguration vbSpeechModelConfiguration = (VbSpeechModelConfiguration) o;
    return Objects.equals(this.language, vbSpeechModelConfiguration.language) &&
        Objects.equals(this.features, vbSpeechModelConfiguration.features) &&
        Objects.equals(this.extensions, vbSpeechModelConfiguration.extensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, features, extensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbSpeechModelConfiguration {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

