/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.VbChannelConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbStereoConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbStereoConfiguration {
  @JsonProperty("left")
  private VbChannelConfiguration left = null;

  @JsonProperty("right")
  private VbChannelConfiguration right = null;

  public VbStereoConfiguration left(VbChannelConfiguration left) {
    this.left = left;
    return this;
  }

   /**
   * Description of the speaker on the left channel (Channel 0)
   * @return left
  **/
  @ApiModelProperty(example = "null", value = "Description of the speaker on the left channel (Channel 0)")
  public VbChannelConfiguration getLeft() {
    return left;
  }

  public void setLeft(VbChannelConfiguration left) {
    this.left = left;
  }

  public VbStereoConfiguration right(VbChannelConfiguration right) {
    this.right = right;
    return this;
  }

   /**
   * Description of the speaker on the right channel (Channel 1)
   * @return right
  **/
  @ApiModelProperty(example = "null", value = "Description of the speaker on the right channel (Channel 1)")
  public VbChannelConfiguration getRight() {
    return right;
  }

  public void setRight(VbChannelConfiguration right) {
    this.right = right;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbStereoConfiguration vbStereoConfiguration = (VbStereoConfiguration) o;
    return Objects.equals(this.left, vbStereoConfiguration.left) &&
        Objects.equals(this.right, vbStereoConfiguration.right);
  }

  @Override
  public int hashCode() {
    return Objects.hash(left, right);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbStereoConfiguration {\n");
    
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

