/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbTranscriptRedactorConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbTranscriptRedactorConfiguration {
  @JsonProperty("replacement")
  private String replacement = null;

  public VbTranscriptRedactorConfiguration replacement(String replacement) {
    this.replacement = replacement;
    return this;
  }

   /**
   * Sequence of characters to replace words within a transcript when reported by a detector
   * @return replacement
  **/
  @ApiModelProperty(example = "null", value = "Sequence of characters to replace words within a transcript when reported by a detector")
  public String getReplacement() {
    return replacement;
  }

  public void setReplacement(String replacement) {
    this.replacement = replacement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbTranscriptRedactorConfiguration vbTranscriptRedactorConfiguration = (VbTranscriptRedactorConfiguration) o;
    return Objects.equals(this.replacement, vbTranscriptRedactorConfiguration.replacement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(replacement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbTranscriptRedactorConfiguration {\n");
    
    sb.append("    replacement: ").append(toIndentedString(replacement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

