/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbChannelConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbTrackConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbTrackConfiguration {
  @JsonProperty("trackIndex")
  private Integer trackIndex = null;

  @JsonProperty("speakerName")
  private String speakerName = null;

  @JsonProperty("speakerRole")
  private String speakerRole = null;

  @JsonProperty("channels")
  private java.util.List<VbChannelConfiguration> channels = new java.util.ArrayList<VbChannelConfiguration>();

  public VbTrackConfiguration trackIndex(Integer trackIndex) {
    this.trackIndex = trackIndex;
    return this;
  }

   /**
   * Track index.
   * @return trackIndex
  **/
  @ApiModelProperty(example = "null", value = "Track index.")
  public Integer getTrackIndex() {
    return trackIndex;
  }

  public void setTrackIndex(Integer trackIndex) {
    this.trackIndex = trackIndex;
  }

  public VbTrackConfiguration speakerName(String speakerName) {
    this.speakerName = speakerName;
    return this;
  }

   /**
   * Speaker name. Defaults to \"Speaker\". If this attribute is specified, all channels are mixed into a single one.
   * @return speakerName
  **/
  @ApiModelProperty(example = "null", value = "Speaker name. Defaults to \"Speaker\". If this attribute is specified, all channels are mixed into a single one.")
  public String getSpeakerName() {
    return speakerName;
  }

  public void setSpeakerName(String speakerName) {
    this.speakerName = speakerName;
  }

  public VbTrackConfiguration speakerRole(String speakerRole) {
    this.speakerRole = speakerRole;
    return this;
  }

   /**
   * A description of the speaker role. Only used as metadata.
   * @return speakerRole
  **/
  @ApiModelProperty(example = "null", value = "A description of the speaker role. Only used as metadata.")
  public String getSpeakerRole() {
    return speakerRole;
  }

  public void setSpeakerRole(String speakerRole) {
    this.speakerRole = speakerRole;
  }

  public VbTrackConfiguration channels(java.util.List<VbChannelConfiguration> channels) {
    this.channels = channels;
    return this;
  }

  public VbTrackConfiguration addChannelsItem(VbChannelConfiguration channelsItem) {
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * List of channels to process, mutually exclusive with \"speakerName\"
   * @return channels
  **/
  @ApiModelProperty(example = "null", value = "List of channels to process, mutually exclusive with \"speakerName\"")
  public java.util.List<VbChannelConfiguration> getChannels() {
    return channels;
  }

  public void setChannels(java.util.List<VbChannelConfiguration> channels) {
    this.channels = channels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbTrackConfiguration vbTrackConfiguration = (VbTrackConfiguration) o;
    return Objects.equals(this.trackIndex, vbTrackConfiguration.trackIndex) &&
        Objects.equals(this.speakerName, vbTrackConfiguration.speakerName) &&
        Objects.equals(this.speakerRole, vbTrackConfiguration.speakerRole) &&
        Objects.equals(this.channels, vbTrackConfiguration.channels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackIndex, speakerName, speakerRole, channels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbTrackConfiguration {\n");
    
    sb.append("    trackIndex: ").append(toIndentedString(trackIndex)).append("\n");
    sb.append("    speakerName: ").append(toIndentedString(speakerName)).append("\n");
    sb.append("    speakerRole: ").append(toIndentedString(speakerRole)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

