/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.VbContentFilteringConfiguration;
import com.voicebase.sample.v3client.model.VbFormattingConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbTranscriptConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbTranscriptConfiguration {
  @JsonProperty("formatting")
  private VbFormattingConfiguration formatting = null;

  @JsonProperty("contentFiltering")
  private VbContentFilteringConfiguration contentFiltering = null;

  public VbTranscriptConfiguration formatting(VbFormattingConfiguration formatting) {
    this.formatting = formatting;
    return this;
  }

   /**
   * Get formatting
   * @return formatting
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbFormattingConfiguration getFormatting() {
    return formatting;
  }

  public void setFormatting(VbFormattingConfiguration formatting) {
    this.formatting = formatting;
  }

  public VbTranscriptConfiguration contentFiltering(VbContentFilteringConfiguration contentFiltering) {
    this.contentFiltering = contentFiltering;
    return this;
  }

   /**
   * Get contentFiltering
   * @return contentFiltering
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbContentFilteringConfiguration getContentFiltering() {
    return contentFiltering;
  }

  public void setContentFiltering(VbContentFilteringConfiguration contentFiltering) {
    this.contentFiltering = contentFiltering;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbTranscriptConfiguration vbTranscriptConfiguration = (VbTranscriptConfiguration) o;
    return Objects.equals(this.formatting, vbTranscriptConfiguration.formatting) &&
        Objects.equals(this.contentFiltering, vbTranscriptConfiguration.contentFiltering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formatting, contentFiltering);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbTranscriptConfiguration {\n");
    
    sb.append("    formatting: ").append(toIndentedString(formatting)).append("\n");
    sb.append("    contentFiltering: ").append(toIndentedString(contentFiltering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

