/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbVocabularyScriptConfiguration;
import com.voicebase.sample.v3client.model.VbVocabularyTermConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbVocabularyConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbVocabularyConfiguration {
  @JsonProperty("vocabularyName")
  private String vocabularyName = null;

  @JsonProperty("terms")
  private java.util.List<VbVocabularyTermConfiguration> terms = new java.util.ArrayList<VbVocabularyTermConfiguration>();

  @JsonProperty("scripts")
  private java.util.List<VbVocabularyScriptConfiguration> scripts = new java.util.ArrayList<VbVocabularyScriptConfiguration>();

  public VbVocabularyConfiguration vocabularyName(String vocabularyName) {
    this.vocabularyName = vocabularyName;
    return this;
  }

   /**
   * Get vocabularyName
   * @return vocabularyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVocabularyName() {
    return vocabularyName;
  }

  public void setVocabularyName(String vocabularyName) {
    this.vocabularyName = vocabularyName;
  }

  public VbVocabularyConfiguration terms(java.util.List<VbVocabularyTermConfiguration> terms) {
    this.terms = terms;
    return this;
  }

  public VbVocabularyConfiguration addTermsItem(VbVocabularyTermConfiguration termsItem) {
    this.terms.add(termsItem);
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabularyTermConfiguration> getTerms() {
    return terms;
  }

  public void setTerms(java.util.List<VbVocabularyTermConfiguration> terms) {
    this.terms = terms;
  }

  public VbVocabularyConfiguration scripts(java.util.List<VbVocabularyScriptConfiguration> scripts) {
    this.scripts = scripts;
    return this;
  }

  public VbVocabularyConfiguration addScriptsItem(VbVocabularyScriptConfiguration scriptsItem) {
    this.scripts.add(scriptsItem);
    return this;
  }

   /**
   * Get scripts
   * @return scripts
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabularyScriptConfiguration> getScripts() {
    return scripts;
  }

  public void setScripts(java.util.List<VbVocabularyScriptConfiguration> scripts) {
    this.scripts = scripts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbVocabularyConfiguration vbVocabularyConfiguration = (VbVocabularyConfiguration) o;
    return Objects.equals(this.vocabularyName, vbVocabularyConfiguration.vocabularyName) &&
        Objects.equals(this.terms, vbVocabularyConfiguration.terms) &&
        Objects.equals(this.scripts, vbVocabularyConfiguration.scripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vocabularyName, terms, scripts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbVocabularyConfiguration {\n");
    
    sb.append("    vocabularyName: ").append(toIndentedString(vocabularyName)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    scripts: ").append(toIndentedString(scripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

