/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.ArrayList;
import com.voicebase.sample.v3client.model.VbFrequency;
import com.voicebase.sample.v3client.model.VbWordTypeEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbWord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbWord {
  @JsonProperty("p")
  private Integer p = null;

  @JsonProperty("c")
  private Double c = null;

  @JsonProperty("s")
  private Long s = null;

  @JsonProperty("e")
  private Long e = null;

  @JsonProperty("frq")
  private java.util.List<VbFrequency> frq = new java.util.ArrayList<VbFrequency>();

  @JsonProperty("m")
  private VbWordTypeEnum m = null;

  @JsonProperty("v")
  private Double v = null;

  @JsonProperty("w")
  private String w = null;

  public VbWord p(Integer p) {
    this.p = p;
    return this;
  }

   /**
   * Get p
   * @return p
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getP() {
    return p;
  }

  public void setP(Integer p) {
    this.p = p;
  }

  public VbWord c(Double c) {
    this.c = c;
    return this;
  }

   /**
   * Get c
   * @return c
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getC() {
    return c;
  }

  public void setC(Double c) {
    this.c = c;
  }

  public VbWord s(Long s) {
    this.s = s;
    return this;
  }

   /**
   * Get s
   * @return s
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getS() {
    return s;
  }

  public void setS(Long s) {
    this.s = s;
  }

  public VbWord e(Long e) {
    this.e = e;
    return this;
  }

   /**
   * Get e
   * @return e
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getE() {
    return e;
  }

  public void setE(Long e) {
    this.e = e;
  }

  public VbWord frq(java.util.List<VbFrequency> frq) {
    this.frq = frq;
    return this;
  }

  public VbWord addFrqItem(VbFrequency frqItem) {
    this.frq.add(frqItem);
    return this;
  }

   /**
   * Get frq
   * @return frq
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbFrequency> getFrq() {
    return frq;
  }

  public void setFrq(java.util.List<VbFrequency> frq) {
    this.frq = frq;
  }

  public VbWord m(VbWordTypeEnum m) {
    this.m = m;
    return this;
  }

   /**
   * Get m
   * @return m
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbWordTypeEnum getM() {
    return m;
  }

  public void setM(VbWordTypeEnum m) {
    this.m = m;
  }

  public VbWord v(Double v) {
    this.v = v;
    return this;
  }

   /**
   * Get v
   * @return v
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getV() {
    return v;
  }

  public void setV(Double v) {
    this.v = v;
  }

  public VbWord w(String w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getW() {
    return w;
  }

  public void setW(String w) {
    this.w = w;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbWord vbWord = (VbWord) o;
    return Objects.equals(this.p, vbWord.p) &&
        Objects.equals(this.c, vbWord.c) &&
        Objects.equals(this.s, vbWord.s) &&
        Objects.equals(this.e, vbWord.e) &&
        Objects.equals(this.frq, vbWord.frq) &&
        Objects.equals(this.m, vbWord.m) &&
        Objects.equals(this.v, vbWord.v) &&
        Objects.equals(this.w, vbWord.w);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p, c, s, e, frq, m, v, w);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbWord {\n");
    
    sb.append("    p: ").append(toIndentedString(p)).append("\n");
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("    e: ").append(toIndentedString(e)).append("\n");
    sb.append("    frq: ").append(toIndentedString(frq)).append("\n");
    sb.append("    m: ").append(toIndentedString(m)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

