/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.api;

import com.voicebase.sample.v3client.ApiException;
import com.voicebase.sample.v3client.model.VbClassifierModel;
import com.voicebase.sample.v3client.model.VbClassifierModelsResponse;
import com.voicebase.sample.v3client.model.VbDetectorModel;
import com.voicebase.sample.v3client.model.VbDetectorModelsResponse;
import com.voicebase.sample.v3client.model.VbErrorResponse;
import com.voicebase.sample.v3client.model.VbKeywordGroup;
import com.voicebase.sample.v3client.model.VbKeywordGroupsResponse;
import com.voicebase.sample.v3client.model.VbSearchableFields;
import com.voicebase.sample.v3client.model.VbVocabulariesResponse;
import com.voicebase.sample.v3client.model.VbVocabulary;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for DefinitionApi
 */
@Ignore
public class DefinitionApiTest {

    private final DefinitionApi api = new DefinitionApi();

    
    /**
     * Create or update keyword spotting group
     *
     * Create or update a keyword spotting group with a set of keywords
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createKeywordSpottingGroupTest() throws ApiException {
        String groupId = null;
        VbKeywordGroup keywordSpottingGroup = null;
        VbKeywordGroup response = api.createKeywordSpottingGroup(groupId, keywordSpottingGroup);

        // TODO: test validations
    }
    
    /**
     * Create or update a custom vocabulary
     *
     * Create or update a custom vocabulary. Custom vocabularies are used to improve accurary of transcription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createVocabularyTest() throws ApiException {
        String vocabularyId = null;
        VbVocabulary vocabulary = null;
        VbVocabulary response = api.createVocabulary(vocabularyId, vocabulary);

        // TODO: test validations
    }
    
    /**
     * Delete keyword spotting group
     *
     * Delete the keyword spotting group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteKeywordSpottingGroupByIdTest() throws ApiException {
        String groupId = null;
        api.deleteKeywordSpottingGroupById(groupId);

        // TODO: test validations
    }
    
    /**
     * Delete a custom vocabulary
     *
     * Delete a custom vocabulary
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteVocabularyByIdTest() throws ApiException {
        String vocabularyId = null;
        api.deleteVocabularyById(vocabularyId);

        // TODO: test validations
    }
    
    /**
     * Retrieve details about a predictive classification model
     *
     * Get the classifier model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClassifierTest() throws ApiException {
        String classifierId = null;
        VbClassifierModel response = api.getClassifier(classifierId);

        // TODO: test validations
    }
    
    /**
     * List predictive classification models
     *
     * List available predictive models for classification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClassifiersTest() throws ApiException {
        VbClassifierModelsResponse response = api.getClassifiers();

        // TODO: test validations
    }
    
    /**
     * Retrieve details about a detection model
     *
     * Retrieve details about a detection model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetectorTest() throws ApiException {
        String detectorId = null;
        VbDetectorModel response = api.getDetector(detectorId);

        // TODO: test validations
    }
    
    /**
     * List detection models
     *
     * List available detection models
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetectorsTest() throws ApiException {
        VbDetectorModelsResponse response = api.getDetectors();

        // TODO: test validations
    }
    
    /**
     * Retrieve a keyword spotting Group
     *
     * Retrieve a keyword spotting group with its keywords
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKeywordSpottingGroupByIdTest() throws ApiException {
        String groupId = null;
        VbKeywordGroup response = api.getKeywordSpottingGroupById(groupId);

        // TODO: test validations
    }
    
    /**
     * List keyword spotting groups
     *
     * Get all defined keyword spotting groups
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKeywordSpottingGroupsTest() throws ApiException {
        VbKeywordGroupsResponse response = api.getKeywordSpottingGroups();

        // TODO: test validations
    }
    
    /**
     * Retrieve the list of extended metadata searchable fields
     *
     * Get searchable fields
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSearchableFieldsTest() throws ApiException {
        VbSearchableFields response = api.getSearchableFields();

        // TODO: test validations
    }
    
    /**
     * List custom vocabularies
     *
     * List all defined custom vocabularies. Custom vocabularies are used to improve accurary of transcription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVocabulariesTest() throws ApiException {
        VbVocabulariesResponse response = api.getVocabularies();

        // TODO: test validations
    }
    
    /**
     * Retrieve a custom vocabulary.
     *
     * Retrieve a custom vocabulary
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVocabularyByIdTest() throws ApiException {
        String vocabularyId = null;
        VbVocabulary response = api.getVocabularyById(vocabularyId);

        // TODO: test validations
    }
    
    /**
     * Define extended metadata searchable fields
     *
     * Create or update custom parameters of metadata for search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setSearchableFieldsTest() throws ApiException {
        VbSearchableFields searchableFields = null;
        VbSearchableFields response = api.setSearchableFields(searchableFields);

        // TODO: test validations
    }
    
}
