/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Sound attributes to replace spoken words in the audio when reported by a detector
 */
@ApiModel(description = "Sound attributes to replace spoken words in the audio when reported by a detector")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbAudioRedactorConfiguration {
  @JsonProperty("tone")
  private Integer tone = null;

  @JsonProperty("gain")
  private Float gain = null;

  public VbAudioRedactorConfiguration tone(Integer tone) {
    this.tone = tone;
    return this;
  }

   /**
   * Get tone
   * @return tone
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTone() {
    return tone;
  }

  public void setTone(Integer tone) {
    this.tone = tone;
  }

  public VbAudioRedactorConfiguration gain(Float gain) {
    this.gain = gain;
    return this;
  }

   /**
   * Get gain
   * @return gain
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getGain() {
    return gain;
  }

  public void setGain(Float gain) {
    this.gain = gain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbAudioRedactorConfiguration vbAudioRedactorConfiguration = (VbAudioRedactorConfiguration) o;
    return Objects.equals(this.tone, vbAudioRedactorConfiguration.tone) &&
        Objects.equals(this.gain, vbAudioRedactorConfiguration.gain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tone, gain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbAudioRedactorConfiguration {\n");
    
    sb.append("    tone: ").append(toIndentedString(tone)).append("\n");
    sb.append("    gain: ").append(toIndentedString(gain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

