/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbClassifier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbClassifier {
  @JsonProperty("classifierId")
  private String classifierId = null;

  @JsonProperty("classifierName")
  private String classifierName = null;

  @JsonProperty("classifierDisplayName")
  private String classifierDisplayName = null;

  @JsonProperty("classifierType")
  private String classifierType = null;

  @JsonProperty("predictedClassLabel")
  private String predictedClassLabel = null;

  @JsonProperty("predictionScore")
  private Double predictionScore = null;

  @JsonProperty("predictedClass")
  private Integer predictedClass = null;

  public VbClassifier classifierId(String classifierId) {
    this.classifierId = classifierId;
    return this;
  }

   /**
   * Get classifierId
   * @return classifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassifierId() {
    return classifierId;
  }

  public void setClassifierId(String classifierId) {
    this.classifierId = classifierId;
  }

  public VbClassifier classifierName(String classifierName) {
    this.classifierName = classifierName;
    return this;
  }

   /**
   * Get classifierName
   * @return classifierName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassifierName() {
    return classifierName;
  }

  public void setClassifierName(String classifierName) {
    this.classifierName = classifierName;
  }

  public VbClassifier classifierDisplayName(String classifierDisplayName) {
    this.classifierDisplayName = classifierDisplayName;
    return this;
  }

   /**
   * Get classifierDisplayName
   * @return classifierDisplayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassifierDisplayName() {
    return classifierDisplayName;
  }

  public void setClassifierDisplayName(String classifierDisplayName) {
    this.classifierDisplayName = classifierDisplayName;
  }

  public VbClassifier classifierType(String classifierType) {
    this.classifierType = classifierType;
    return this;
  }

   /**
   * Get classifierType
   * @return classifierType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassifierType() {
    return classifierType;
  }

  public void setClassifierType(String classifierType) {
    this.classifierType = classifierType;
  }

  public VbClassifier predictedClassLabel(String predictedClassLabel) {
    this.predictedClassLabel = predictedClassLabel;
    return this;
  }

   /**
   * Get predictedClassLabel
   * @return predictedClassLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPredictedClassLabel() {
    return predictedClassLabel;
  }

  public void setPredictedClassLabel(String predictedClassLabel) {
    this.predictedClassLabel = predictedClassLabel;
  }

  public VbClassifier predictionScore(Double predictionScore) {
    this.predictionScore = predictionScore;
    return this;
  }

   /**
   * Get predictionScore
   * @return predictionScore
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPredictionScore() {
    return predictionScore;
  }

  public void setPredictionScore(Double predictionScore) {
    this.predictionScore = predictionScore;
  }

  public VbClassifier predictedClass(Integer predictedClass) {
    this.predictedClass = predictedClass;
    return this;
  }

   /**
   * Get predictedClass
   * @return predictedClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPredictedClass() {
    return predictedClass;
  }

  public void setPredictedClass(Integer predictedClass) {
    this.predictedClass = predictedClass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbClassifier vbClassifier = (VbClassifier) o;
    return Objects.equals(this.classifierId, vbClassifier.classifierId) &&
        Objects.equals(this.classifierName, vbClassifier.classifierName) &&
        Objects.equals(this.classifierDisplayName, vbClassifier.classifierDisplayName) &&
        Objects.equals(this.classifierType, vbClassifier.classifierType) &&
        Objects.equals(this.predictedClassLabel, vbClassifier.predictedClassLabel) &&
        Objects.equals(this.predictionScore, vbClassifier.predictionScore) &&
        Objects.equals(this.predictedClass, vbClassifier.predictedClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classifierId, classifierName, classifierDisplayName, classifierType, predictedClassLabel, predictionScore, predictedClass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbClassifier {\n");
    
    sb.append("    classifierId: ").append(toIndentedString(classifierId)).append("\n");
    sb.append("    classifierName: ").append(toIndentedString(classifierName)).append("\n");
    sb.append("    classifierDisplayName: ").append(toIndentedString(classifierDisplayName)).append("\n");
    sb.append("    classifierType: ").append(toIndentedString(classifierType)).append("\n");
    sb.append("    predictedClassLabel: ").append(toIndentedString(predictedClassLabel)).append("\n");
    sb.append("    predictionScore: ").append(toIndentedString(predictionScore)).append("\n");
    sb.append("    predictedClass: ").append(toIndentedString(predictedClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

