/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbClass
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbClass {
  @JsonProperty("classLabel")
  private String classLabel = null;

  @JsonProperty("classValue")
  private Integer classValue = null;

  public VbClass classLabel(String classLabel) {
    this.classLabel = classLabel;
    return this;
  }

   /**
   * Get classLabel
   * @return classLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClassLabel() {
    return classLabel;
  }

  public void setClassLabel(String classLabel) {
    this.classLabel = classLabel;
  }

  public VbClass classValue(Integer classValue) {
    this.classValue = classValue;
    return this;
  }

   /**
   * Get classValue
   * @return classValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getClassValue() {
    return classValue;
  }

  public void setClassValue(Integer classValue) {
    this.classValue = classValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbClass vbClass = (VbClass) o;
    return Objects.equals(this.classLabel, vbClass.classLabel) &&
        Objects.equals(this.classValue, vbClass.classValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classLabel, classValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbClass {\n");
    
    sb.append("    classLabel: ").append(toIndentedString(classLabel)).append("\n");
    sb.append("    classValue: ").append(toIndentedString(classValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

