/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbDetectedSegment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbDetection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbDetection {
  @JsonProperty("detectorClass")
  private Integer detectorClass = null;

  @JsonProperty("detectorClassLabel")
  private String detectorClassLabel = null;

  @JsonProperty("detectedSegments")
  private java.util.List<VbDetectedSegment> detectedSegments = new java.util.ArrayList<VbDetectedSegment>();

  public VbDetection detectorClass(Integer detectorClass) {
    this.detectorClass = detectorClass;
    return this;
  }

   /**
   * Get detectorClass
   * @return detectorClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDetectorClass() {
    return detectorClass;
  }

  public void setDetectorClass(Integer detectorClass) {
    this.detectorClass = detectorClass;
  }

  public VbDetection detectorClassLabel(String detectorClassLabel) {
    this.detectorClassLabel = detectorClassLabel;
    return this;
  }

   /**
   * Get detectorClassLabel
   * @return detectorClassLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDetectorClassLabel() {
    return detectorClassLabel;
  }

  public void setDetectorClassLabel(String detectorClassLabel) {
    this.detectorClassLabel = detectorClassLabel;
  }

  public VbDetection detectedSegments(java.util.List<VbDetectedSegment> detectedSegments) {
    this.detectedSegments = detectedSegments;
    return this;
  }

  public VbDetection addDetectedSegmentsItem(VbDetectedSegment detectedSegmentsItem) {
    this.detectedSegments.add(detectedSegmentsItem);
    return this;
  }

   /**
   * Get detectedSegments
   * @return detectedSegments
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbDetectedSegment> getDetectedSegments() {
    return detectedSegments;
  }

  public void setDetectedSegments(java.util.List<VbDetectedSegment> detectedSegments) {
    this.detectedSegments = detectedSegments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbDetection vbDetection = (VbDetection) o;
    return Objects.equals(this.detectorClass, vbDetection.detectorClass) &&
        Objects.equals(this.detectorClassLabel, vbDetection.detectorClassLabel) &&
        Objects.equals(this.detectedSegments, vbDetection.detectedSegments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectorClass, detectorClassLabel, detectedSegments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbDetection {\n");
    
    sb.append("    detectorClass: ").append(toIndentedString(detectorClass)).append("\n");
    sb.append("    detectorClassLabel: ").append(toIndentedString(detectorClassLabel)).append("\n");
    sb.append("    detectedSegments: ").append(toIndentedString(detectedSegments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

