/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbDiarization
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbDiarization {
  @JsonProperty("band")
  private String band = null;

  @JsonProperty("env")
  private String env = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("length")
  private Long length = null;

  @JsonProperty("speakerLabel")
  private String speakerLabel = null;

  @JsonProperty("start")
  private Long start = null;

  public VbDiarization band(String band) {
    this.band = band;
    return this;
  }

   /**
   * Get band
   * @return band
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBand() {
    return band;
  }

  public void setBand(String band) {
    this.band = band;
  }

  public VbDiarization env(String env) {
    this.env = env;
    return this;
  }

   /**
   * Get env
   * @return env
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEnv() {
    return env;
  }

  public void setEnv(String env) {
    this.env = env;
  }

  public VbDiarization gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public VbDiarization length(Long length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLength() {
    return length;
  }

  public void setLength(Long length) {
    this.length = length;
  }

  public VbDiarization speakerLabel(String speakerLabel) {
    this.speakerLabel = speakerLabel;
    return this;
  }

   /**
   * Get speakerLabel
   * @return speakerLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpeakerLabel() {
    return speakerLabel;
  }

  public void setSpeakerLabel(String speakerLabel) {
    this.speakerLabel = speakerLabel;
  }

  public VbDiarization start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbDiarization vbDiarization = (VbDiarization) o;
    return Objects.equals(this.band, vbDiarization.band) &&
        Objects.equals(this.env, vbDiarization.env) &&
        Objects.equals(this.gender, vbDiarization.gender) &&
        Objects.equals(this.length, vbDiarization.length) &&
        Objects.equals(this.speakerLabel, vbDiarization.speakerLabel) &&
        Objects.equals(this.start, vbDiarization.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(band, env, gender, length, speakerLabel, start);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbDiarization {\n");
    
    sb.append("    band: ").append(toIndentedString(band)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    speakerLabel: ").append(toIndentedString(speakerLabel)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

