/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.voicebase.sample.v3client.model.VbAudioRedactorConfiguration;
import com.voicebase.sample.v3client.model.VbTranscriptRedactorConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbRedactorConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbRedactorConfiguration {
  @JsonProperty("transcript")
  private VbTranscriptRedactorConfiguration transcript = null;

  @JsonProperty("audio")
  private VbAudioRedactorConfiguration audio = null;

  public VbRedactorConfiguration transcript(VbTranscriptRedactorConfiguration transcript) {
    this.transcript = transcript;
    return this;
  }

   /**
   * Get transcript
   * @return transcript
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbTranscriptRedactorConfiguration getTranscript() {
    return transcript;
  }

  public void setTranscript(VbTranscriptRedactorConfiguration transcript) {
    this.transcript = transcript;
  }

  public VbRedactorConfiguration audio(VbAudioRedactorConfiguration audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Get audio
   * @return audio
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbAudioRedactorConfiguration getAudio() {
    return audio;
  }

  public void setAudio(VbAudioRedactorConfiguration audio) {
    this.audio = audio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbRedactorConfiguration vbRedactorConfiguration = (VbRedactorConfiguration) o;
    return Objects.equals(this.transcript, vbRedactorConfiguration.transcript) &&
        Objects.equals(this.audio, vbRedactorConfiguration.audio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transcript, audio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbRedactorConfiguration {\n");
    
    sb.append("    transcript: ").append(toIndentedString(transcript)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

