/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbStream
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbStream {
  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("streamName")
  private String streamName = null;

  @JsonProperty("streamLocation")
  private String streamLocation = null;

  @JsonProperty("comment")
  private String comment = null;

  public VbStream status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public VbStream streamName(String streamName) {
    this.streamName = streamName;
    return this;
  }

   /**
   * Get streamName
   * @return streamName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStreamName() {
    return streamName;
  }

  public void setStreamName(String streamName) {
    this.streamName = streamName;
  }

  public VbStream streamLocation(String streamLocation) {
    this.streamLocation = streamLocation;
    return this;
  }

   /**
   * Get streamLocation
   * @return streamLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStreamLocation() {
    return streamLocation;
  }

  public void setStreamLocation(String streamLocation) {
    this.streamLocation = streamLocation;
  }

  public VbStream comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbStream vbStream = (VbStream) o;
    return Objects.equals(this.status, vbStream.status) &&
        Objects.equals(this.streamName, vbStream.streamName) &&
        Objects.equals(this.streamLocation, vbStream.streamLocation) &&
        Objects.equals(this.comment, vbStream.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, streamName, streamLocation, comment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbStream {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    streamName: ").append(toIndentedString(streamName)).append("\n");
    sb.append("    streamLocation: ").append(toIndentedString(streamLocation)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

