/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbVocabulary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbVocabulariesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbVocabulariesResponse {
  @JsonProperty("vocabularies")
  private java.util.List<VbVocabulary> vocabularies = new java.util.ArrayList<VbVocabulary>();

  public VbVocabulariesResponse vocabularies(java.util.List<VbVocabulary> vocabularies) {
    this.vocabularies = vocabularies;
    return this;
  }

  public VbVocabulariesResponse addVocabulariesItem(VbVocabulary vocabulariesItem) {
    this.vocabularies.add(vocabulariesItem);
    return this;
  }

   /**
   * Get vocabularies
   * @return vocabularies
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabulary> getVocabularies() {
    return vocabularies;
  }

  public void setVocabularies(java.util.List<VbVocabulary> vocabularies) {
    this.vocabularies = vocabularies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbVocabulariesResponse vbVocabulariesResponse = (VbVocabulariesResponse) o;
    return Objects.equals(this.vocabularies, vbVocabulariesResponse.vocabularies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vocabularies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbVocabulariesResponse {\n");
    
    sb.append("    vocabularies: ").append(toIndentedString(vocabularies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

