/*
 * Voicebase V3 API
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.voicebase.sample.v3client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.ArrayList;
import com.voicebase.sample.v3client.model.VbVocabularyScript;
import com.voicebase.sample.v3client.model.VbVocabularyTerm;
import com.voicebase.sample.v3client.model.VbVocabularyType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VbVocabulary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-12T18:19:19.705-07:00")
public class VbVocabulary {
  @JsonProperty("vocabularyName")
  private String vocabularyName = null;

  @JsonProperty("vocabularyType")
  private VbVocabularyType vocabularyType = null;

  @JsonProperty("terms")
  private java.util.List<VbVocabularyTerm> terms = new java.util.ArrayList<VbVocabularyTerm>();

  @JsonProperty("scripts")
  private java.util.List<VbVocabularyScript> scripts = new java.util.ArrayList<VbVocabularyScript>();

  public VbVocabulary vocabularyName(String vocabularyName) {
    this.vocabularyName = vocabularyName;
    return this;
  }

   /**
   * Get vocabularyName
   * @return vocabularyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVocabularyName() {
    return vocabularyName;
  }

  public void setVocabularyName(String vocabularyName) {
    this.vocabularyName = vocabularyName;
  }

  public VbVocabulary vocabularyType(VbVocabularyType vocabularyType) {
    this.vocabularyType = vocabularyType;
    return this;
  }

   /**
   * Get vocabularyType
   * @return vocabularyType
  **/
  @ApiModelProperty(example = "null", value = "")
  public VbVocabularyType getVocabularyType() {
    return vocabularyType;
  }

  public void setVocabularyType(VbVocabularyType vocabularyType) {
    this.vocabularyType = vocabularyType;
  }

  public VbVocabulary terms(java.util.List<VbVocabularyTerm> terms) {
    this.terms = terms;
    return this;
  }

  public VbVocabulary addTermsItem(VbVocabularyTerm termsItem) {
    this.terms.add(termsItem);
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabularyTerm> getTerms() {
    return terms;
  }

  public void setTerms(java.util.List<VbVocabularyTerm> terms) {
    this.terms = terms;
  }

  public VbVocabulary scripts(java.util.List<VbVocabularyScript> scripts) {
    this.scripts = scripts;
    return this;
  }

  public VbVocabulary addScriptsItem(VbVocabularyScript scriptsItem) {
    this.scripts.add(scriptsItem);
    return this;
  }

   /**
   * Get scripts
   * @return scripts
  **/
  @ApiModelProperty(example = "null", value = "")
  public java.util.List<VbVocabularyScript> getScripts() {
    return scripts;
  }

  public void setScripts(java.util.List<VbVocabularyScript> scripts) {
    this.scripts = scripts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VbVocabulary vbVocabulary = (VbVocabulary) o;
    return Objects.equals(this.vocabularyName, vbVocabulary.vocabularyName) &&
        Objects.equals(this.vocabularyType, vbVocabulary.vocabularyType) &&
        Objects.equals(this.terms, vbVocabulary.terms) &&
        Objects.equals(this.scripts, vbVocabulary.scripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vocabularyName, vocabularyType, terms, scripts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VbVocabulary {\n");
    
    sb.append("    vocabularyName: ").append(toIndentedString(vocabularyName)).append("\n");
    sb.append("    vocabularyType: ").append(toIndentedString(vocabularyType)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    scripts: ").append(toIndentedString(scripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

